export interface AnakRecord {
  id: string;
  nama: string;
  nik: string;
  usiaBulan: number;
  jenisKelamin: "L" | "P";
  namaOrangTua: string;
  beratBadan: number;
  tinggiBadan: number;
  zScoreTBU: string;
  zScoreBBU: string;
  zScoreBBTB: string;
  statusGizi: "Normal" | "Gizi Kurang" | "Gizi Buruk" | "Stunting";
  rekomendasiAI: string;
  tanggalPeriksa: string;
}

export const dataAnak: AnakRecord[] = [
  {
    id: "1",
    nama: "Muhammad Arfan",
    nik: "3201948392010001",
    usiaBulan: 28,
    jenisKelamin: "L",
    namaOrangTua: "Rahmat Hidayat",
    beratBadan: 10.1,
    tinggiBadan: 78.5,
    zScoreTBU: "-3.1 SD",
    zScoreBBU: "-2.8 SD",
    zScoreBBTB: "-1.5 SD",
    statusGizi: "Stunting",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Terindikasi Stunting Berat. Disarankan evaluasi asupan kalori & rujukan medis ke Faskes.",
    tanggalPeriksa: "2026-08-12",
  },
  {
    id: "2",
    nama: "Aisyah Putri Humaira",
    nik: "3201948392010002",
    usiaBulan: 14,
    jenisKelamin: "P",
    namaOrangTua: "Hendra Wijaya",
    beratBadan: 8.1,
    tinggiBadan: 71.2,
    zScoreTBU: "-2.4 SD",
    zScoreBBU: "-2.1 SD",
    zScoreBBTB: "-1.2 SD",
    statusGizi: "Stunting",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Terindikasi Stunting Moderate. Diberikan PMT protein hewani (2 telur/hari).",
    tanggalPeriksa: "2026-08-11",
  },
  {
    id: "3",
    nama: "Kenzo Rafasya",
    nik: "3201948392010003",
    usiaBulan: 32,
    jenisKelamin: "L",
    namaOrangTua: "Ferry Irawan",
    beratBadan: 11.2,
    tinggiBadan: 89.5,
    zScoreTBU: "-1.9 SD",
    zScoreBBU: "-1.8 SD",
    zScoreBBTB: "-0.9 SD",
    statusGizi: "Gizi Kurang",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Terindikasi Gizi Kurang. Tingkatkan porsi makan gizi seimbang & vitamin tambahan.",
    tanggalPeriksa: "2026-08-10",
  },
  {
    id: "4",
    nama: "Andi Saputra",
    nik: "3201948392010004",
    usiaBulan: 39,
    jenisKelamin: "L",
    namaOrangTua: "Budi Saputra",
    beratBadan: 9.2,
    tinggiBadan: 74.0,
    zScoreTBU: "-2.3 SD",
    zScoreBBU: "-1.8 SD",
    zScoreBBTB: "-1.1 SD",
    statusGizi: "Gizi Kurang",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Diberikan konseling gizi dan pendampingan intensif Posyandu.",
    tanggalPeriksa: "2026-08-09",
  },
  {
    id: "5",
    nama: "Dafa Ibrahim",
    nik: "3201948392010005",
    usiaBulan: 12,
    jenisKelamin: "L",
    namaOrangTua: "Ibrahim Hasan",
    beratBadan: 7.2,
    tinggiBadan: 68.0,
    zScoreTBU: "-3.2 SD",
    zScoreBBU: "-3.0 SD",
    zScoreBBTB: "-2.2 SD",
    statusGizi: "Gizi Buruk",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] KRITIS! Terindikasi Gizi Buruk. Segera rujuk ke Puskesmas setempat.",
    tanggalPeriksa: "2026-08-08",
  },
  {
    id: "6",
    nama: "Hanif Abdillah",
    nik: "3201948392010006",
    usiaBulan: 19,
    jenisKelamin: "L",
    namaOrangTua: "Abdullah Mansur",
    beratBadan: 13.2,
    tinggiBadan: 79.5,
    zScoreTBU: "+0.8 SD",
    zScoreBBU: "+0.9 SD",
    zScoreBBTB: "+0.7 SD",
    statusGizi: "Normal",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan optimal. Pertahankan pola makan gizi seimbang.",
    tanggalPeriksa: "2026-08-07",
  },
  {
    id: "7",
    nama: "Siti Nurbaya",
    nik: "3201948392010007",
    usiaBulan: 18,
    jenisKelamin: "P",
    namaOrangTua: "Ahmad Nurdin",
    beratBadan: 10.5,
    tinggiBadan: 81.0,
    zScoreTBU: "+0.2 SD",
    zScoreBBU: "+0.1 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Status gizi normal. Pertahankan asupan ASI/makanan gizi seimbang.",
    tanggalPeriksa: "2026-08-06",
  },
  {
    id: "8",
    nama: "Bagas Pratama",
    nik: "3201948392010008",
    usiaBulan: 24,
    jenisKelamin: "L",
    namaOrangTua: "Surya Pratama",
    beratBadan: 12.0,
    tinggiBadan: 86.5,
    zScoreTBU: "+0.1 SD",
    zScoreBBU: "+0.3 SD",
    zScoreBBTB: "+0.2 SD",
    statusGizi: "Normal",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan sangat baik. Lanjutkan pemantauan Posyandu rutin.",
    tanggalPeriksa: "2026-08-05",
  },
  {
    id: "9",
    nama: "Rania Putri",
    nik: "3201948392010009",
    usiaBulan: 10,
    jenisKelamin: "P",
    namaOrangTua: "Dedi Suhendar",
    beratBadan: 8.5,
    tinggiBadan: 72.0,
    zScoreTBU: "0.0 SD",
    zScoreBBU: "0.0 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Indikator gizi seimbang sesuai grafik WHO.",
    tanggalPeriksa: "2026-08-04",
  },
  {
    id: "10",
    nama: "Daffa Alfarizqi",
    nik: "3201948392010010",
    usiaBulan: 36,
    jenisKelamin: "L",
    namaOrangTua: "Irwan Alfarizqi",
    beratBadan: 13.5,
    tinggiBadan: 94.0,
    zScoreTBU: "-0.1 SD",
    zScoreBBU: "-0.2 SD",
    zScoreBBTB: "-0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan optimal.",
    tanggalPeriksa: "2026-08-03",
  },
  {
    id: "11",
    nama: "Zahra Amelia",
    nik: "3201948392010011",
    usiaBulan: 15,
    jenisKelamin: "P",
    namaOrangTua: "Agus Setiawan",
    beratBadan: 9.0,
    tinggiBadan: 75.5,
    zScoreTBU: "+0.3 SD",
    zScoreBBU: "+0.2 SD",
    zScoreBBTB: "+0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Status gizi baik.",
    tanggalPeriksa: "2026-08-02",
  },
  {
    id: "12",
    nama: "Fathir Ahmad",
    nik: "3201948392010012",
    usiaBulan: 42,
    jenisKelamin: "L",
    namaOrangTua: "Taufik Hidayat",
    beratBadan: 14.2,
    tinggiBadan: 98.0,
    zScoreTBU: "0.0 SD",
    zScoreBBU: "+0.1 SD",
    zScoreBBTB: "+0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Status gizi normal.",
    tanggalPeriksa: "2026-08-01",
  },
  {
    id: "13",
    nama: "Nayla Khairunnisa",
    nik: "3201948392010013",
    usiaBulan: 20,
    jenisKelamin: "P",
    namaOrangTua: "Eko Prasetyo",
    beratBadan: 10.2,
    tinggiBadan: 80.5,
    zScoreTBU: "0.0 SD",
    zScoreBBU: "-0.1 SD",
    zScoreBBTB: "-0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Tumbuh kembang baik.",
    tanggalPeriksa: "2026-07-31",
  },
  {
    id: "14",
    nama: "Rizky Ramadhan",
    nik: "3201948392010014",
    usiaBulan: 30,
    jenisKelamin: "L",
    namaOrangTua: "Herman Ramadhan",
    beratBadan: 11.8,
    tinggiBadan: 88.0,
    zScoreTBU: "-0.4 SD",
    zScoreBBU: "-0.5 SD",
    zScoreBBTB: "-0.3 SD",
    statusGizi: "Normal",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Pertahankan pola makan sehat.",
    tanggalPeriksa: "2026-07-30",
  },
  {
    id: "15",
    nama: "Ghaida Nur",
    nik: "3201948392010015",
    usiaBulan: 16,
    jenisKelamin: "P",
    namaOrangTua: "Rizal Nur",
    beratBadan: 9.5,
    tinggiBadan: 77.0,
    zScoreTBU: "+0.1 SD",
    zScoreBBU: "0.0 SD",
    zScoreBBTB: "-0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI:
      "[ANALISIS MEDIS KEMENKES RI & WHO] Pertahankan pola makan bergizi seimbang.",
    tanggalPeriksa: "2026-07-29",
  },
  {
    id: "16",
    nama: "Alya Ramadhani",
    nik: "3201948392010016",
    usiaBulan: 22,
    jenisKelamin: "P",
    namaOrangTua: "Rahmat Ramadhani",
    beratBadan: 10.8,
    tinggiBadan: 83.0,
    zScoreTBU: "+0.2 SD",
    zScoreBBU: "+0.1 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Status gizi normal. Lanjutkan pola makan seimbang.",
    tanggalPeriksa: "2026-07-28",
  },
  {
    id: "17",
    nama: "Bintang Pratama",
    nik: "3201948392010017",
    usiaBulan: 35,
    jenisKelamin: "L",
    namaOrangTua: "Dwi Pratama",
    beratBadan: 12.5,
    tinggiBadan: 90.0,
    zScoreTBU: "-2.5 SD",
    zScoreBBU: "-2.0 SD",
    zScoreBBTB: "-1.0 SD",
    statusGizi: "Stunting",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Terindikasi Stunting. Rujuk untuk intervensi gizi.",
    tanggalPeriksa: "2026-07-27",
  },
  {
    id: "18",
    nama: "Cantika Sari",
    nik: "3201948392010018",
    usiaBulan: 11,
    jenisKelamin: "P",
    namaOrangTua: "Hadi Sari",
    beratBadan: 8.0,
    tinggiBadan: 70.5,
    zScoreTBU: "-0.3 SD",
    zScoreBBU: "-0.2 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan baik.",
    tanggalPeriksa: "2026-07-26",
  },
  {
    id: "19",
    nama: "Dimas Ardiansyah",
    nik: "3201948392010019",
    usiaBulan: 40,
    jenisKelamin: "L",
    namaOrangTua: "Ardiansyah",
    beratBadan: 10.0,
    tinggiBadan: 85.0,
    zScoreTBU: "-2.7 SD",
    zScoreBBU: "-2.5 SD",
    zScoreBBTB: "-1.8 SD",
    statusGizi: "Gizi Kurang",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Perlu intervensi PMT dan pendampingan gizi.",
    tanggalPeriksa: "2026-07-25",
  },
  {
    id: "20",
    nama: "Elsa Maharani",
    nik: "3201948392010020",
    usiaBulan: 26,
    jenisKelamin: "P",
    namaOrangTua: "Joko Maharani",
    beratBadan: 11.5,
    tinggiBadan: 85.5,
    zScoreTBU: "+0.4 SD",
    zScoreBBU: "+0.3 SD",
    zScoreBBTB: "+0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Status gizi sangat baik.",
    tanggalPeriksa: "2026-07-24",
  },
  {
    id: "21",
    nama: "Farhan Maulana",
    nik: "3201948392010021",
    usiaBulan: 9,
    jenisKelamin: "L",
    namaOrangTua: "Maulana Syah",
    beratBadan: 7.0,
    tinggiBadan: 67.0,
    zScoreTBU: "-3.0 SD",
    zScoreBBU: "-2.8 SD",
    zScoreBBTB: "-2.0 SD",
    statusGizi: "Gizi Buruk",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] KRITIS! Segera rujuk ke Puskesmas untuk tatalaksana gizi buruk.",
    tanggalPeriksa: "2026-07-23",
  },
  {
    id: "22",
    nama: "Gita Puspita",
    nik: "3201948392010022",
    usiaBulan: 17,
    jenisKelamin: "P",
    namaOrangTua: "Agung Puspita",
    beratBadan: 9.8,
    tinggiBadan: 78.0,
    zScoreTBU: "+0.1 SD",
    zScoreBBU: "+0.2 SD",
    zScoreBBTB: "+0.1 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Tumbuh kembang sesuai kurva WHO.",
    tanggalPeriksa: "2026-07-22",
  },
  {
    id: "23",
    nama: "Haikal Firmansyah",
    nik: "3201948392010023",
    usiaBulan: 45,
    jenisKelamin: "L",
    namaOrangTua: "Firmansyah",
    beratBadan: 14.8,
    tinggiBadan: 99.0,
    zScoreTBU: "-0.2 SD",
    zScoreBBU: "-0.1 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan optimal sesuai usia.",
    tanggalPeriksa: "2026-07-21",
  },
  {
    id: "24",
    nama: "Intan Permata",
    nik: "3201948392010024",
    usiaBulan: 13,
    jenisKelamin: "P",
    namaOrangTua: "Rudi Permata",
    beratBadan: 7.5,
    tinggiBadan: 69.0,
    zScoreTBU: "-2.6 SD",
    zScoreBBU: "-2.3 SD",
    zScoreBBTB: "-1.5 SD",
    statusGizi: "Stunting",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Terindikasi Stunting. Berikan PMT protein hewani.",
    tanggalPeriksa: "2026-07-20",
  },
  {
    id: "25",
    nama: "Jihan Aulia",
    nik: "3201948392010025",
    usiaBulan: 31,
    jenisKelamin: "P",
    namaOrangTua: "Saiful Aulia",
    beratBadan: 12.0,
    tinggiBadan: 88.5,
    zScoreTBU: "-0.5 SD",
    zScoreBBU: "-0.3 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Status gizi baik. Lanjutkan.",
    tanggalPeriksa: "2026-07-19",
  },
  {
    id: "26",
    nama: "Kevin Saputra",
    nik: "3201948392010026",
    usiaBulan: 38,
    jenisKelamin: "L",
    namaOrangTua: "Andi Saputra",
    beratBadan: 15.5,
    tinggiBadan: 96.0,
    zScoreTBU: "+0.5 SD",
    zScoreBBU: "+0.6 SD",
    zScoreBBTB: "+0.4 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan optimal. Pertahankan pola asuh dan nutrisi.",
    tanggalPeriksa: "2026-07-18",
  },
  {
    id: "27",
    nama: "Laila Azzahra",
    nik: "3201948392010027",
    usiaBulan: 21,
    jenisKelamin: "P",
    namaOrangTua: "Bambang Azzahra",
    beratBadan: 10.3,
    tinggiBadan: 82.0,
    zScoreTBU: "+0.3 SD",
    zScoreBBU: "+0.2 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Tumbuh kembang sangat baik.",
    tanggalPeriksa: "2026-07-17",
  },
  {
    id: "28",
    nama: "Muhammad Raffi",
    nik: "3201948392010028",
    usiaBulan: 27,
    jenisKelamin: "L",
    namaOrangTua: "Deni Raffi",
    beratBadan: 9.5,
    tinggiBadan: 79.0,
    zScoreTBU: "-2.3 SD",
    zScoreBBU: "-2.0 SD",
    zScoreBBTB: "-1.2 SD",
    statusGizi: "Gizi Kurang",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Tambahkan porsi protein hewani dan karbohidrat kompleks.",
    tanggalPeriksa: "2026-07-16",
  },
  {
    id: "29",
    nama: "Nadia Safitri",
    nik: "3201948392010029",
    usiaBulan: 8,
    jenisKelamin: "P",
    namaOrangTua: "Wahyu Safitri",
    beratBadan: 7.8,
    tinggiBadan: 68.5,
    zScoreTBU: "+0.2 SD",
    zScoreBBU: "+0.1 SD",
    zScoreBBTB: "0.0 SD",
    statusGizi: "Normal",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Pertumbuhan sesuai kurva WHO.",
    tanggalPeriksa: "2026-07-15",
  },
  {
    id: "30",
    nama: "Omar Fadhilah",
    nik: "3201948392010030",
    usiaBulan: 33,
    jenisKelamin: "L",
    namaOrangTua: "Fadhilah Rahman",
    beratBadan: 11.0,
    tinggiBadan: 86.0,
    zScoreTBU: "-2.8 SD",
    zScoreBBU: "-2.5 SD",
    zScoreBBTB: "-1.8 SD",
    statusGizi: "Stunting",
    rekomendasiAI: "[ANALISIS MEDIS KEMENKES RI & WHO] Terindikasi Stunting Berat. Segera rujuk ke Faskes.",
    tanggalPeriksa: "2026-07-14",
  },
];
